# This configuration file determines what is shown per object radial
# 
# The values here are returned as JSON via /metadata/radial/:klass
#
# Valid attributes (* required)
#   tasks: - A named task (see user_tasks.yml) !! Limit this to 3 or 4 
#   recent: - defaults to true if not provided, if false no recent list is shown
#   allow_destroy: - false if no
#   edit: over-ride data->edit
#   new: over-ride data->new
#   home: where requested, use this path rather than show
#
---
AssertedDistribution:
  tasks:
    - asserted_distributions_basic_endemism_task 
    - new_asserted_distribution_from_map_task
  config:
    recent: true
Combination:
  tasks:
    - browse_nomenclature_task
    - new_combination_task
    - otu_distribution_data_task
  edit: new_combination_task
  new: new_combination_task
  config:
    recent: true
CollectionObject:
  tasks:
    - browse_collection_objects_task
    - comprehensive_collection_object_task
    - browse_collecting_events_task
    - collection_objects_filter_task
    - build_biocuration_groups_task
    - report_dwc_task
  config: 
    recent: true
  edit: comprehensive_collection_object_task
  new: comprehensive_collection_object_task
CollectingEvent:
  tasks:
    - browse_collecting_events_task
    - comprehensive_collection_object_task
    - filter_collecting_events_task
  config: 
    recent: true
Descriptor:
  tasks:
    - observation_matrix_hub_task
  new: new_descriptor_task
  edit: new_descriptor_task
Document:
  tasks:
    - gnfinder_task
  config: 
    recent: true
GeographicArea:
  tasks:
    - asserted_distributions_basic_endemism_task 
  config:
    recent: false
Loan:
  tasks:
    - overdue_loans_task
    - edit_loan_task
  config:
    recent: true
ObservationMatrix:
  tasks:
    - new_matrix_task
    - new_descriptor_task
    - observation_matrices_hub_task
  config:
    recent: true    
Otu:
  tasks:
    - browse_otus_task
    - comprehensive_collection_object_task
    - otus_filter_task
    - cite_otus_task_task
    - index_browse_asserted_distributions_task 
    - otu_distribution_data_task
    - index_editor_task
  config:
    recent: true
Person:
  tasks:
    - uniquify_people_task
  config:
    recent: true
Source:
  tasks:
    - source_hub_task
    - new_source_task
    - filter_sources_task   
    - nomenclature_by_source_task
    - gnfinder_task
  new: new_source_task
  edit: new_source_task
  config:
    recent: true
TaxonName:
  tasks:
    - new_combination_task
    - edit_type_material_task
    - comprehensive_collection_object_task
    - browse_otus_task
    - browse_nomenclature_task
    - new_taxon_name_task
    - index_stats_task
    - otu_distribution_data_task
    - asserted_distributions_basic_endemism_task
  edit: new_taxon_name_task
  new: new_taxon_name_task
  config:
    recent: true
