FROM mdillon/postgis:11

ENV POSTGRES_HOST_AUTH_METHOD=trust

RUN {\
  echo "psql -U postgres -c 'CREATE EXTENSION postgis; CREATE EXTENSION postgis_topology;'"; \
} > /docker-entrypoint-initdb.d/setup-postgis-extensions.sh
