name: Ruby

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.5
    - name: Update apt cache
      run: sudo apt-get update
    - name: Install apt packages
      run: sudo apt-get install -y imagemagick tesseract-ocr libgeos-dev libproj-dev postgresql-10-postgis-2.4
    - name: Build and test with Rake
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake
