name: Ruby

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        worker: [0, 1, 2, 3, 4]
    services:
      db:
        image: mdillon/postgis:11
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.5
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install apt packages
      run: |
        sudo apt-get update
        sudo apt-get install -y imagemagick tesseract-ocr libgeos-dev libproj-dev
    - name: Set up TaxonWorks
      run: |
        cp config/application_settings.yml.travis config/application_settings.yml
        cp config/secrets.yml.example config/secrets.yml
        cp config/database.yml.github config/database.yml
    - name: Build and run tests
      env:
        RAILS_ENV: test
        TEST_WORKER: ${{ matrix.worker }}
        TEST_WORKERS: 5
      run: |
        npm install
        gem install bundler
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
        bundle exec rake db:create
        bundle exec rake db:migrate
        .travis/spec_runner.sh
