name: Ruby

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.5
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Install apt packages
      run: |
        sudo apt-get update
        sudo apt-get install -y imagemagick tesseract-ocr libgeos-dev libproj-dev postgis
    - name: Set up TaxonWorks (Just using Travis configs as-is for now)
      run: |
        cp config/secrets.yml.example config/secrets.yml
        cp config/database.yml.github config/database.yml
    - name: Build and run tests
      env:
        DATABASE_URL: postgres://postgres:@localhost:5432/test
        RAILS_ENV: test
      run: |
        gem install bundler
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
        bundle exec rake db:create
        bundle exec rake db:gis:setup
        bundle exec rake db:migrate
        bundle exec rails test
